### ISSUE TITLE
quota mail warning doesn't stay checked

### ISSUE THREAD

**Issue by julian70400** [nextcloud/quota_warning#71] opened 2021-04-09 10:30 UTC
### Steps to reproduce
1. activate quota mail warning
2. change page
3. return to quota page

### Expected behaviour
Quota mail warning stay checked

### Actual behaviour
Quota mail warning is not checked when I reload the page or change page

### Server configuration

**Operating system**:
Linux app5.gl-amf.org 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
**Web server:**
nginx version: nginx/1.14.2
**Database:**
Server version: 10.3.27-MariaDB-0+deb10u1 Debian 10
**PHP version:**
7.4.16

**Nextcloud version:** (see Nextcloud admin page)
nextcloud 21.0.0 and 21.0.1

**Where did you install Nextcloud from:**
from nextcloud repo

**List of activated apps:**

Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - breezedark: 21.0.6
  - calendar: 2.2.0
  - circles: 0.21.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - event_update_notification: 1.2.0
  - external: 3.8.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_antivirus: 3.2.0
  - files_downloadactivity: 1.10.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - group_default_quota: 0.1.0
  - group_everyone: 0.1.7
  - groupfolders: 9.0.0
  - groupquota: 0.1.5
  - impersonate: 1.8.0
  - login_notes: 0.4.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.10.0
  - ransomware_protection: 1.10.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.1.1
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - talk_simple_poll: 1.3.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - user_usage_report: 1.5.0
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - deck
  - drop_account
  - encryption
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - photos
  - recommendations
  - support
  - survey_client
  - unsplash
  - user_ldap
  - weather_status

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.fm"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/nc.fm",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "default_phone_region": "FR",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows
### Logs
no error log, nowhere

**Comment by nickvergessen** [comment] 2021-04-09 10:42
Duplicate of #65

**Closed by nickvergessen** 2021-04-09 10:42 UTC
